baseURL = "https://example.com"
title = "yxzoe's website"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "xyzoe"
    badge = "green"
    quote = "blue"
    index_posts_num = 5
    google_search = true
    # logo = "cat.jpeg"
    bio = """
    <p> This is a simple blog for learning R. </p>
    <br />
    <p>Also all html tags such as <a href="https://github.com/ertuil/erblog">link</a> are a good here.</p>
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

 [[menu.main]]
     identifier = "My GitHub"
     name = "My GitHub"
     url = "https://github.com/yxzoe/yxzoe.github.io"
     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "2608156297@qq.com"
    name = "E-mail"
    weight = 1

[[menu.icon]]
    url = "https://github.com/yxzoe/yxzoe.github.io"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://user.qzone.qq.com/2608156297/main"
    name = "Q-Zone"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/username/"
    name = "instagram"
    weight = 1
