baseURL = "https://example.com"
title = "yxzoe's blog"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "yxzoe周雨欣"
    badge = "orange"
    quote = "red"
    index_posts_num = 5
    google_search = true
    # logo = "//themes/erblog/static/self/img/cat.jpeg"
    bio = """
    <p> This is a simple website for R learning. </p>
    <br />
    <p>Welcome to contact me through <a href="https://github.com/yxzoe">github</a> although there's little content.</p>
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "GitHub"
#     name = "GitHub"
#     url = "https://github.com/yxzoe"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:username@mail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/username"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/username/"
    name = "instagram"
    weight = 1
