---
title: 第二章：R语言的数据结构
author: 'yxzoe'
date: '2020-05-26'
slug: r语言的数据结构
categories: []
tags: []
---
# 2-1 对象和属性

## R语言对象的5种基本类型（classes of object)：
-	 字符(character)
-	 数值(numeric:real numbers)
-	 整数(integer)
-	 复数(complex):1+2i
-	 逻辑(logical:True/False)

## Rstudio实操

1. 创建数值型数值（赋值）：x=1   →    x <- 1  回车即可。
（99%的情况下，赋值用x=1也是会报错的，但是在一些极端的情况下不得行，所以一般还是使用箭头）

- 查看x的值：输入x，回车，得到 [1]
  此处的[1]代表，它后面的元素是x的第一个元素；后面的1代表x中存储的内容是1
  
- 查看数据类型的函数“class”：输入“class（x）”回车，得到 [1] "numeric" ,意思是：x是一个数值型变量，且x的值可以是整数或小数

2. 创建整数型数值：”numeric“一般表示数值，如果想强调数值是”整数“，在赋值时，在数值后面加一个L即可。
例如：x <- 2L，回车，再用class查看数据类型，英文会变成”integer“

 *R对字母大小写非常敏感，X与x将产生两个不同的变量，使用时要非常注意*

3. 创建字符型数值：输入y<- "hello"（比数值型多一对双引号），回车即可。此时用class(y)得到的英文就是“character"字符型

4. 创建逻辑型数值：输入t <-TRUE，回车即可（在R里，TRUE/FALSE都必须用大写）

5. 创建复数型字符：输入x<-1+2i，回车，此时x的数据类型就是“complex”。（用的比较少）

## R的对象的属性

- 名称(name)
- 维度(dimensions: matrix, array)
- 类型(class)
- 长度(length)

# 2-2 向量（vector）

## 数据结构：
- 向量（vector)：可包含多个元素，但这些元素必须属于同一种数据类型
- （代码都是一次性的，如果想重复利用某组代码，就要新建一个脚本文件，把代码保存在里面）为了让文件更有可读性，一般会用“#"来注释

## 创建向量的方法：

1. x <- **vector**("character",  length = 10) ，即括号内是数值的类型和向量的长度。在控制台内输入这个，回车即可运行命令；而在脚本文件中，需要鼠标选中这一行命令，再点击文本框右上角的“run”来运行命令，得到一个有10个位置的空向量

2. x1 <- 1:4 ,运行命令即创建一个内容为数值1-4的向量x1，int[1:4] 1 2 3 4

3. x2 <- c(1,2,3,4),括号里是向量中每个元素的内容，运行得到一个包含1，2，3，4的向量x2, num[1:4] 1 2 3 4 。  【不用太在意int和num的区别，反正都是代表数字】
- 当函数c后的括号里输入的元素的数值类型不同，R会强制把这些元素变成同一个类型。例如：x3 <- c(TRUE, 10, "A")，运行后显示的x3将是chr [1:3] "TRUE" "10" "A"，也就是R把三个元素强制都归为了字符型
- 用命令强制更换某个向量的数值类型：x4 <-c("a", "b", "c")回车换行，输入as . numeric(x4),运行，这就是强制把x4从字符型变成数值型。而此时控制台会出现警告信息，提示引入了NA，即空值，意思是R系统不知道如何把abc这三个字符转换成数字，所以就用空值NA代替。同理，如果想转换成其他类型，只需把as 后面的numeric换成logical、character等英文就好了

## 用names函数给向量添加名称：

- 之前创建了一个包含4个元素的向量x1, 输入**names**(x1) <- c("a", "b", "c", "d")，运行命令即完成命名。在控制台输入x1回车就能看到元素的名称对应

# 2-3 矩阵和数组（matrix & array）

## 矩阵

- 矩阵（matrix):向量+维度属性（一个包含两个元素的整数向量：nrow行数, ncol列数)
- 涉及的函数有：**matrix(), vector()+dim(),cbind(),rbind(),attributes()**
用右上板块的小扫把logo清除以前的变量信息，防止旧变量干扰新操作

## 创建矩阵：

1. x <- **matrix**(nrow = 3, ncol = 2),即括号内是行数和列数，运行后，右侧框出现矩阵，这个矩阵里都是空值；
2. 在控制台输入x回车，就能看到3行2列的矩阵；
3. 在行数前添加参数，即矩阵的内容，如 x <- matrix(1:6, nrow = 3, ncol = 2),运行得如下矩阵
4. 矩阵内容是按列来填充的
5. 矩阵的维度属性dim，运行dim(x)就能在控制台看到矩阵有几行几列
6. 想看当前矩阵有多少属性、有哪些属性：函数attributes(x),运行后在控制台能看到当前矩阵x的属性为维度

## 拼接两个矩阵

1. 创建新矩阵y2, 使用**rbind**（y,y2)，就是以行拼接两个矩阵
2. **cbind**（y,y2)则是以列拼接，运行得如下2行6列的矩阵

## 数组

- 数组（array)：与矩阵类似，但是维度可以大于2（矩阵只能等于2）
	• 用**array**函数创建数组

## 	创建数组：

- array后面第一个参数是数组内容，第二个是用dim来设置维度，用c进行维度拼接，如下命令是建立一个4行6列的二维数组。运行后得到的既是一个矩阵也是一个数组
- 在c后面多加一个参数，创建一个三维的数组，

# 2-4 列表（list）

- 可以包含不同类型的对象


## 	创建列表：

- 用**list（）**函数
- l <- list(“a", 2, 10L, 3+4i, TRUE)括号内为列表每一个参数的内容
- 这个列表包含五个元素，他们的类型分别为字符、数值、整数、复数、逻辑
- 给列表里的元素命名，list(元素名=元素内容），名称从123变成了abc
- 创建 每个元素包含的内容>1 的列表：c(元素内包含的内容)

## 引进新维度dimnames：

- 用matrix创建一个矩阵x，用dimnames函数和list函数来为矩阵命名

# 2-5 因子（factor）
- 处理分类数据。分类数据可分为有序/无序
  - 有序：年级、高中低→可以比大小
  - 无序：男女性别→不能不大小
- 可以把因子理解为  整数型向量+标签（label）即可以对这个整数向量进行描述解释
  - 比如Male/Female可以用1/2表示，但是如果光用整数向量表示，很容易遗忘这里的1、2代表什么意思，而存为factor就可以对1、2增加描述
	- 常用于lm(), glm()
	
## 创建因子：

- **factor（c(因子内容））**
- *level*是因子的一个属性，这个因子有两个水平（levels），分别为female和male
-  设定基线水平：创建因子y，在c后面添加第二个参数levels
- y和x的区别在于levels里男女的先后顺序，排在第一个的叫“基线水平”
- 用**table**函数查看因子整体信息
- 用**unclass**函数去掉因子的属性
- 此时因子x里的男女水平被去掉，控制台会显示以前的属性是“levels”，内容是“female”“male”。
- 去掉标签后的因子，用class函数查看数据类型，变成了整数向量（integer）

# 2-6  缺失值（missing value)
- NA/NaN（注意大写）
- NaN属于NA，一般用于表示数字的缺失值；而NA可表示的缺失值范围更广
- NA有类型属性，如integer NA， character NA等

##判断一个向量是否有缺失值：
is.na()/is.nan()
- 创建一个向量x，里面的内容是1，NA,2,NA,3
- is.na(x)如果是缺失值返回真（TRUE），不是缺失值返回假（FALSE）
	 Is.nan返回的全是false，说明向量x里没有NaN类型的缺失值，nan识别不出NA
	 把x里的NA换成NaN，两者的输出结果一致，即na可以检测出NaN

# 2-7  数据框（data frame)

- 用于存储表格数据（tabular data）
- 可以把数据框视为 各元素长度相等的一种列表形式：每个元素代表一列数据，每个元素的长度代表行数，元素类型可以不同

##创建数据框：
df <- data.frame()
- 每个参数代表每一列的内容。第一个参数命名为id，内容为1234；第二列叫name，内容为字符型的abcd；第三列叫gender，TRUE表示男性
- df <- data.frame(id = c(1,2,3,4), name = c("a","b","c","d"),gender = c(TRUE,TRUE,FALSE,FALSE)

## 	 数据框和矩阵的区别：
矩阵里每一行的元素都是同一个类型的，而数据框里，一行三个元素类型各不相同
## 用nrow和ncol查看数据框有多少行多少列

# 2-8   日期与时间（date，time）

1. 日期 Date：距离1970-01-01的天数/date()/Sys.Date()/weekdays()/months()/quarters()
-  用date()查询，会根据时区、电脑时间设置变化
-  用Sys.Date()查询，只有年月日；此时x2为日期类型
-  将任意日期存储为Date格式：as.Date("年-月-日“），注意用-连接，月日用两位数

## 日期查询：
- 某个日期是星期几：weekdays()
- 某个日期是几月：months（）
- 某个日期属于哪个季度：quarters（） Q1为该年第一季度
- 某个日期距离1970年1月1日多少天：julian()

## 计算某两个日期之间相隔多少天：
- 将两个Date类型的数值相减。
   - 若只想得到365这个数字不想要一句话，就强行把计算结果转化为numeric数值形式

2.时间 POSIXct/POSIXlt：距离1970-01-01的秒数/Sys.time()
-  POSIXct：存储的是整数，数据常被存入数据框中
-  POSIXlt：存储为列表，还包含星期、年、月、日等信息
-  Sys.time()，最后的CST为时区，数据类型为POSIXct
将POSIXct与POSIXlt相互转换：x本为POSIXct格式，用**as.POSIXlt**(x)转换；把lt换成ct就as.POSIXct就行了

##查看lt这个类型里存了哪些内容：
names内容名称，unclass去掉p的属性留下p的内容
##将任意格式的时间字符串转化为Date格式：
strptime()
 月份%B，日%d，年%Y，时%H，月%M，其他标点与x1一致





