---
title: 第四章：操纵数据：重要函数的使用
author: yxzoe
date: '2020-05-27'
slug: 操纵数据-重要函数的使用
categories: []
tags: []
---

# 4-1  R语言函数lapply
- 处理循环
  - R不仅有for/while循环语句，还有一句话就能实现循环的函数
- 排序
- 总结数据信息

## 1.lapply
- 可以循环处理列表中每一个元素
- lapply(列表，函数/函数名，其他参数）, 结果总是返回一个列表

## str()函数：
- 将任意R对象以一种简洁紧凑的方式呈现出来
- function意思是函数，x是列表，FUN是你要进行怎样的处理
1. 创建一个列表x
- mean是求平均，lapply分别对x中的a、b元素求平均值
-  sapply是对lapply的结果进行化简（能化简的情况下）
	- 当结果列表元素长度均为1，返回向量
	- 当列表元素长度相同且大于1，返回矩阵
	- 当长度不相同则无法化简，结果和lapply一样
-sapply把lapply返回的列表简化成了一个向量 
2. 创建向量x，值为1~4
  - runif意思是从一个均匀分布的总体里抽取若干个数出来
	- 当x值为1时，抽出来1个数；x为2时，抽出来2个数，以此类推
	- 虽然x是向量不是列表，但在lapply中会自动强制转化为列表
	- min和max是对前面的runif进行限定
	- runif默认是从0~1进行抽取，这样设定后就从0~100抽取了
	
# 4-2  R语言函数apply
## apply：沿着数组的某一维度处理数据
- 例如：将函数用于矩阵的行或列, 虽然与for/while循环的效率相似，但是只用一句话就可以完成

##apply（数组，维度，函数/函数名）
- 创建一个矩阵
- apply(x,2,mean)  意思是沿着x的第2个维度求平均
- 矩阵的第一个维度是行，第二个维度是列，因此这里的意思就是，对矩阵x的列求平均
- 求列的和只需把mean换成sum
##更简单的方法求行/列的和/平均
- rowSums(x)
- rowMeans(x)
- colSums(x)
- colMeans(x)

##创建一个矩阵
- rnorm意思是随机从正态分布的总体里抽取100个数
- 后面的10，10意思是把这100个数排成10×10的矩阵
- quantile意思是求数据的百分位点
- probs是对quantile进行限定，要求25%和75%百分位点所对应的数据

# 4-3  R语言函数mapply
- lapply的多元版本
## mapply（函数/函数名，数据，函数相关参数）
- 创建一个列表，内容是4个1，3个2，2个3，1个4，用rep函数
- 用mapply就只要用一次rep，数据是1~4，数量是4~1
## 如何自定义函数：
- 函数命名为s，function代表它是一个函数，n表示要从正态分布总体中抽取的个数，mean代表随机分布总体的均值，std代表随机分布代表的标准差
- 在花括号{}中输入函数体。用rnorm函数，这个函数的意思是，从均值为mean，标准差为std的总体里抽取n个数据
-把这三行代码运行一下就可以调用它了
- 如s(4,0,1)，意思是从均值为0，标准差为1的正态分布里抽取4个数据
## 与mapply结合，
- 第二个参数1：5对应s中第一个参数，也就是抽几个数；
- 5：1对应s的第二个参数，即分布均值；
- 2就是标准差
- 运行后得到5个元素，第一个元素1个数，第二个2个，第五个元素5个数据
- 且第一个元素来自均值为5，标准差为2的总体
- 第二个元素的数据来自均值为4，标准差为2 的总体
- 第五个元素来自均值为1，标准差为2的总体 

# 4-4  R语言函数tapply
 对向量的子集进行操作
## tapply（向量，因子/因子列表，函数/函数名）
- 创建向量x，x包含15个元素，前5个元素来自正态分布，中间5个元素来自均匀分布，后5个来自均值为1，标准差为0的正态分布
- 创建因子f，用gl函数，第一个参数3表示这个因子有几个水平，第二个参数5表示每个水平下有多少个元素
-  把向量x按照因子f的水平分组，对每一组的数据求平均
- 其中1下面是x中前5个数据的均值

- tapply里有一个默认为真的参数simplify，把原本返回的列表简化成向量
- 如果把simplify设置为假，运行得到的就是一个没有化简的列表
- 可以把mean换成别的，实现对分组数据的不同操作

# 4-5  R语言函数split
 根据因子或因子列表将向量或其他对象分组
- 通常与lapply一起使用
## split（向量/列表/数据框，因子/因子列表）
- 以上一节的向量x，因子f为例
- 用split函数得到一个列表，1代表f中的水平1，对应的5个元素是f的水平1对应的x的前5个元素
- 在lapply里传入已经分好组的列表，对每个元素求平均，下面三个数据就分别是分组之后的5个数据的平均值
## 对数据框使用split：
- 以月份month，将airquality的数据分组（airquality有6个变量，月份是其中一个）
- 首先在split中传入数据框airq，分组依据是airq中的月份month（用$连接）
- 把split的结果存入s中,	得到的就是以月份按月份分组的空气质量数据了
- 想知道airquality中一共有几个月份的数据、每个月份下有几条记录：**table**函数

# 4-6  R语言函数 排序
- sort：对向量进行排序，返回排好序的内容
- order：返回排好序的内容的下标/多个排序标准

## 创建一个数据框x
- 若要把第二列v2按升序排列：sort(x$v2)
- 按降序排列：在后面加decreasing = TRUE
- oder返回的其实是678910对应的行号
- x方括号，后面再加个逗号，意思是返回的行要按照order排序之后的结果
- 可以看到返回的结果前面的行号是order返回的顺序
- 用order按多个标准排序：
- 排序的首要标准是v4，如果v4遇到两个同样的数据排不了,就按v2排
- 若想按降序排列，只需在后面加一个decreasing = TRUE就可以了

# 4-7  R语言函数 总结数据信息
-  head是看数据前6行，tail是看最后6行;在后面加第二个参数10，就能看到前10行
-  summary函数得到airquality中每一个变量的最小值、25%分位点、中位数、均值、75%分位点、最大值、存在的缺失值个数
-  str以一种简洁的方式把airquality的数据进行了总结：数据框；一共有153次记录；6个变量
-  table把month传进去，就是对airquality的月份进行总结
-  把month换成臭氧含量，第一行是臭氧含量取值，第二行是这个值出现的次数
- 若想把NA加进总结，就加第二个参数useNA = ifany,在返回的结果最后会有一个缺失值出现次数的总结
- 传入多个变量。第一行是天数，第一列是月份，第二列第二个1代表5月1日，有1次记录
## 是否有缺失值：
	any(is.na),如果是true则一定有，false一定没有
- any改成sum就是缺失值的个数
## 	 交叉表：
xtabs(想得到的内容 ~ 条件，数据）
## 获取函数的大小（内存）：
object.size()
## 换单位：
用print后面单位unit设置成kb就可以了



